// <auto-generated />
using System;
using HealthCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCare.Migrations
{
    [DbContext(typeof(HealthCareDbContext))]
    [Migration("20260304144332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthCare.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppointmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 3, 9, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8055),
                            AppointmentTime = new DateTime(2026, 3, 10, 0, 43, 32, 476, DateTimeKind.Utc).AddTicks(8061),
                            AppointmentTypeId = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8062),
                            DoctorId = 1,
                            Location = "Medical Center, Building A, Room 302",
                            Notes = "Annual checkup",
                            PatientId = 1,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 11, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8063),
                            AppointmentTime = new DateTime(2026, 3, 12, 4, 43, 32, 476, DateTimeKind.Utc).AddTicks(8064),
                            AppointmentTypeId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8065),
                            DoctorId = 2,
                            Location = "Online Consultation",
                            Notes = "Follow-up appointment",
                            PatientId = 2,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.AppointmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7906),
                            Department = "Primary Care",
                            Description = "Comprehensive health checkup and consultation with experienced physicians",
                            DurationInMinutes = 30,
                            IsActive = true,
                            Price = 75m,
                            TypeCode = "GC",
                            TypeName = "General Consultation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7908),
                            Department = "Specialist Care",
                            Description = "Heart health assessment with ECG and expert consultation",
                            DurationInMinutes = 45,
                            IsActive = true,
                            Price = 150m,
                            TypeCode = "CC",
                            TypeName = "Cardiology Checkup"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7910),
                            Department = "Specialist Care",
                            Description = "Skin care consultation and treatment planning",
                            DurationInMinutes = 30,
                            IsActive = true,
                            Price = 100m,
                            TypeCode = "DC",
                            TypeName = "Dermatology Consultation"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7911),
                            Department = "Virtual Care",
                            Description = "Online video consultation with healthcare professionals",
                            DurationInMinutes = 20,
                            IsActive = true,
                            Price = 50m,
                            TypeCode = "TV",
                            TypeName = "Telemedicine Visit"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7740),
                            DepartmentCode = "PC",
                            DepartmentName = "Primary Care",
                            Description = "General healthcare services",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7743),
                            DepartmentCode = "SC",
                            DepartmentName = "Specialist Care",
                            Description = "Specialized healthcare services",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7744),
                            DepartmentCode = "VC",
                            DepartmentName = "Virtual Care",
                            Description = "Telemedicine and virtual consultations",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8002),
                            DepartmentId = 2,
                            Email = "sarah.johnson@hospital.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            LicenseNumber = "MD-001",
                            PhoneNumber = "555-1001",
                            Speciality = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8004),
                            DepartmentId = 1,
                            Email = "michael.chen@hospital.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            LicenseNumber = "MD-002",
                            PhoneNumber = "555-1002",
                            Speciality = "General Practice"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8006),
                            DepartmentId = 2,
                            Email = "emily.brown@hospital.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Brown",
                            LicenseNumber = "MD-003",
                            PhoneNumber = "555-1003",
                            Speciality = "Dermatology"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.DoctorDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultationDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("QualificationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("DoctorDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationDuration = "45 min",
                            ConsultationFee = 150m,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8029),
                            DoctorId = 1,
                            Experience = "15 years",
                            QualificationDetails = "MD, Board Certified in Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            ConsultationDuration = "30 min",
                            ConsultationFee = 75m,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8030),
                            DoctorId = 2,
                            Experience = "10 years",
                            QualificationDetails = "MD, General Practice"
                        },
                        new
                        {
                            Id = 3,
                            ConsultationDuration = "30 min",
                            ConsultationFee = 100m,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(8032),
                            DoctorId = 3,
                            Experience = "12 years",
                            QualificationDetails = "MD, Board Certified in Dermatology"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7943),
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Doe",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7946),
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Smith",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7948),
                            DateOfBirth = new DateTime(1975, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.j@example.com",
                            FirstName = "Michael",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Johnson",
                            PhoneNumber = "555-0103"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.PatientDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergiesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistoryNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            BloodType = "O+",
                            City = "New York",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7977),
                            EmergencyContactName = "Mary Doe",
                            EmergencyContactPhone = "555-0104",
                            PatientId = 1,
                            PostalCode = "10001",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            BloodType = "A+",
                            City = "Boston",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7979),
                            EmergencyContactName = "John Smith",
                            EmergencyContactPhone = "555-0105",
                            PatientId = 2,
                            PostalCode = "02101",
                            State = "MA"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd",
                            BloodType = "B+",
                            City = "Chicago",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 4, 14, 43, 32, 476, DateTimeKind.Utc).AddTicks(7981),
                            EmergencyContactName = "Sarah Johnson",
                            EmergencyContactPhone = "555-0106",
                            PatientId = 3,
                            PostalCode = "60601",
                            State = "IL"
                        });
                });

            modelBuilder.Entity("HealthCare.Data.Models.Appointment", b =>
                {
                    b.HasOne("HealthCare.Data.Models.AppointmentType", "AppointmentType")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentType");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCare.Data.Models.Doctor", b =>
                {
                    b.HasOne("HealthCare.Data.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HealthCare.Data.Models.DoctorDetails", b =>
                {
                    b.HasOne("HealthCare.Data.Models.Doctor", "Doctor")
                        .WithOne("DoctorDetails")
                        .HasForeignKey("HealthCare.Data.Models.DoctorDetails", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthCare.Data.Models.PatientDetails", b =>
                {
                    b.HasOne("HealthCare.Data.Models.Patient", "Patient")
                        .WithOne("PatientDetails")
                        .HasForeignKey("HealthCare.Data.Models.PatientDetails", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCare.Data.Models.AppointmentType", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthCare.Data.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HealthCare.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorDetails");
                });

            modelBuilder.Entity("HealthCare.Data.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PatientDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
